<h1>Imports

In [387]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

sns.set_theme()

<h1>Data Collection

In [388]:
url = "https://cdn.theforage.com/vinternships/companyassets/Zbnc2o4ok6kD2NEXx/2kCX23cgKgCumeEam/1721851467492/Customer_Churn_Data_Large.xlsx"

excel = pd.ExcelFile(url)

In [389]:
print(excel.sheet_names)

['Customer_Demographics', 'Transaction_History', 'Customer_Service', 'Online_Activity', 'Churn_Status']

In [390]:
df1 = pd.read_excel(url, sheet_name=0)
df2 = pd.read_excel(url, sheet_name=1)
df3 = pd.read_excel(url, sheet_name=2)
df4 = pd.read_excel(url, sheet_name=3)
df5 = pd.read_excel(url, sheet_name=4)

<h1>Data PreProcessing

<h2>DF1

In [391]:
df1

     CustomerID  Age Gender MaritalStatus IncomeLevel
0             1   62      M        Single         Low
1             2   65      M       Married         Low
2             3   18      M        Single         Low
3             4   21      M       Widowed         Low
4             5   21      M      Divorced      Medium
..          ...  ...    ...           ...         ...
995         996   54      F        Single         Low
996         997   19      M       Widowed        High
997         998   47      M       Married         Low
998         999   23      M       Widowed        High
999        1000   34      M       Widowed         Low

[1000 rows x 5 columns]

In [392]:
df1.isnull().sum()

CustomerID       0
Age              0
Gender           0
MaritalStatus    0
IncomeLevel      0
dtype: int64

In [393]:
df1.duplicated().sum()

np.int64(0)

In [394]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     1000 non-null   int64
 1   Age            1000 non-null   int64
 2   Gender         1000 non-null   str
 3   MaritalStatus  1000 non-null   str
 4   IncomeLevel    1000 non-null   str
dtypes: int64(2), str(3)
memory usage: 39.2 KB

In [395]:
df1.describe()

        CustomerID          Age
count  1000.000000  1000.000000
mean    500.500000    43.267000
std     288.819436    15.242311
min       1.000000    18.000000
25%     250.750000    30.000000
50%     500.500000    43.000000
75%     750.250000    56.000000
max    1000.000000    69.000000

In [396]:
new_df1 = df1.copy()
new_df1['Gender'] = new_df1['Gender'].map({'M':0, 'F':1})
new_df1['IncomeLevel'] =  new_df1['IncomeLevel'].map({'Low':0, 'Medium':1, 'High':2})
new_df1 = pd.get_dummies(new_df1, columns=['MaritalStatus'],drop_first=True, dtype=int)

new_df1

,CustomerID,Age,Gender,IncomeLevel,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed
0,1,62,0,0,0,1,0
1,2,65,0,0,1,0,0
2,3,18,0,0,0,1,0
3,4,21,0,0,0,0,1
4,5,21,0,1,0,0,0
...,...,...,...,...,...,...,...
995,996,54,1,0,0,1,0
996,997,19,0,2,0,0,1
997,998,47,0,0,1,0,0
998,999,23,0,2,0,0,1
999,1000,34,0,0,0,0,1

In [397]:
new_df1.describe()

,CustomerID,Age,Gender,IncomeLevel,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.00000
mean,500.500000,43.267000,0.513000,1.024000,0.2610,0.215000,0.27600
std,288.819436,15.242311,0.500081,0.821035,0.4394,0.411028,0.44724
min,1.000000,18.000000,0.000000,0.000000,0.0000,0.000000,0.00000
25%,250.750000,30.000000,0.000000,0.000000,0.0000,0.000000,0.00000
50%,500.500000,43.000000,1.000000,1.000000,0.0000,0.000000,0.00000
75%,750.250000,56.000000,1.000000,2.000000,1.0000,0.000000,1.00000
max,1000.000000,69.000000,1.000000,2.000000,1.0000,1.000000,1.00000

<h2>DF2

In [398]:
df2

      CustomerID  TransactionID TransactionDate  AmountSpent ProductCategory
0              1           7194      2022-03-27       416.50     Electronics
1              2           7250      2022-08-08        54.96        Clothing
2              2           9660      2022-07-25       197.50     Electronics
3              2           2998      2022-01-25       101.31       Furniture
4              2           1228      2022-07-24       397.37        Clothing
...          ...            ...             ...          ...             ...
5049        1000           2724      2022-09-08       232.06       Groceries
5050        1000           2917      2022-12-13       324.98           Books
5051        1000           2979      2022-06-15       375.34       Groceries
5052        1000           8594      2022-04-08       166.73           Books
5053        1000           5529      2022-11-23        93.73       Furniture

[5054 rows x 5 columns]

In [399]:
df2.isnull().sum()

CustomerID         0
TransactionID      0
TransactionDate    0
AmountSpent        0
ProductCategory    0
dtype: int64

In [400]:
df2.duplicated().sum()

np.int64(0)

In [401]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5054 entries, 0 to 5053
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       5054 non-null   int64
 1   TransactionID    5054 non-null   int64
 2   TransactionDate  5054 non-null   datetime64[us]
 3   AmountSpent      5054 non-null   float64
 4   ProductCategory  5054 non-null   str
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 197.6 KB

In [402]:
df2.describe()

        CustomerID  TransactionID             TransactionDate  AmountSpent
count  5054.000000    5054.000000                        5054  5054.000000
mean    501.424218    5510.538979  2022-07-01 19:25:37.158686   250.707351
min       1.000000    1000.000000         2022-01-01 00:00:00     5.180000
25%     251.000000    3242.000000         2022-04-03 00:00:00   127.105000
50%     506.000000    5530.000000         2022-07-01 00:00:00   250.525000
75%     749.000000    7680.750000         2022-09-29 00:00:00   373.412500
max    1000.000000    9997.000000         2022-12-31 00:00:00   499.860000
std     285.172780    2582.088012                         NaN   142.250838

In [403]:
new_df2 = df2.copy()
new_df2 = pd.get_dummies(new_df2, columns=['ProductCategory'],drop_first=True, dtype=int)

<h4>Standardization

In [404]:
scaler_am = StandardScaler()
new_df2['AmountSpent'] = scaler_am.fit_transform(new_df2[['AmountSpent']])

In [405]:
new_df2

,CustomerID,TransactionID,TransactionDate,AmountSpent,ProductCategory_Clothing,ProductCategory_Electronics,ProductCategory_Furniture,ProductCategory_Groceries
0,1,7194,2022-03-27,1.165610,0,1,0,0
1,2,7250,2022-08-08,-1.376208,1,0,0,0
2,2,9660,2022-07-25,-0.374076,0,1,0,0
3,2,2998,2022-01-25,-1.050343,0,0,1,0
4,2,1228,2022-07-24,1.031116,1,0,0,0
...,...,...,...,...,...,...,...,...
5049,1000,2724,2022-09-08,-0.131101,0,0,0,1
5050,1000,2917,2022-12-13,0.522176,0,0,0,0
5051,1000,2979,2022-06-15,0.876234,0,0,0,1
5052,1000,8594,2022-04-08,-0.590405,0,0,0,0
5053,1000,5529,2022-11-23,-1.103634,0,0,1,0

<h2>DF3

In [406]:
df3

,CustomerID,InteractionID,InteractionDate,InteractionType,ResolutionStatus
0,1,6363,2022-03-31,Inquiry,Resolved
1,2,3329,2022-03-17,Inquiry,Resolved
2,3,9976,2022-08-24,Inquiry,Resolved
3,4,7354,2022-11-18,Inquiry,Resolved
4,4,5393,2022-07-03,Inquiry,Unresolved
...,...,...,...,...,...
997,990,3671,2022-10-25,Complaint,Unresolved
998,992,2114,2022-09-29,Feedback,Unresolved
999,994,3087,2022-07-02,Complaint,Unresolved
1000,994,8508,2022-05-14,Complaint,Unresolved
1001,995,9101,2022-05-02,Inquiry,Resolved

In [407]:
df3.isnull().sum()

CustomerID          0
InteractionID       0
InteractionDate     0
InteractionType     0
ResolutionStatus    0
dtype: int64

In [408]:
df3.duplicated().sum()

np.int64(0)

In [409]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        1002 non-null   int64
 1   InteractionID     1002 non-null   int64
 2   InteractionDate   1002 non-null   datetime64[us]
 3   InteractionType   1002 non-null   str
 4   ResolutionStatus  1002 non-null   str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 39.3 KB

In [410]:
df3.describe()

        CustomerID  InteractionID             InteractionDate
count  1002.000000    1002.000000                        1002
mean    485.209581    5952.887226  2022-07-02 19:28:22.994012
min       1.000000    2015.000000         2022-01-01 00:00:00
25%     238.250000    3991.500000         2022-04-07 00:00:00
50%     474.500000    5911.500000         2022-07-02 12:00:00
75%     735.750000    7908.250000         2022-09-30 00:00:00
max     995.000000    9997.000000         2022-12-30 00:00:00
std     287.030259    2305.819681                         NaN

In [411]:
new_df3 = df3.copy()
new_df3 = pd.get_dummies(new_df3, columns=['InteractionType'],drop_first=True, dtype=int)
new_df3 = pd.get_dummies(new_df3, columns=['ResolutionStatus'],drop_first=True, dtype=int)

new_df3

,CustomerID,InteractionID,InteractionDate,InteractionType_Feedback,InteractionType_Inquiry,ResolutionStatus_Unresolved
0,1,6363,2022-03-31,0,1,0
1,2,3329,2022-03-17,0,1,0
2,3,9976,2022-08-24,0,1,0
3,4,7354,2022-11-18,0,1,0
4,4,5393,2022-07-03,0,1,1
...,...,...,...,...,...,...
997,990,3671,2022-10-25,0,0,1
998,992,2114,2022-09-29,1,0,1
999,994,3087,2022-07-02,0,0,1
1000,994,8508,2022-05-14,0,0,1
1001,995,9101,2022-05-02,0,1,0

<h2>DF4

In [412]:
df4

     CustomerID LastLoginDate  LoginFrequency ServiceUsage
0             1    2023-10-21              34   Mobile App
1             2    2023-12-05               5      Website
2             3    2023-11-15               3      Website
3             4    2023-08-25               2      Website
4             5    2023-10-27              41      Website
..          ...           ...             ...          ...
995         996    2023-01-29              38   Mobile App
996         997    2023-04-01               5   Mobile App
997         998    2023-07-10              47      Website
998         999    2023-01-08              23      Website
999        1000    2023-08-13              22   Mobile App

[1000 rows x 4 columns]

In [413]:
df4.describe()

        CustomerID        LastLoginDate  LoginFrequency
count  1000.000000                 1000     1000.000000
mean    500.500000  2023-07-05 21:28:48       25.912000
min       1.000000  2023-01-01 00:00:00        1.000000
25%     250.750000  2023-04-08 00:00:00       13.750000
50%     500.500000  2023-07-10 12:00:00       27.000000
75%     750.250000  2023-10-01 06:00:00       38.000000
max    1000.000000  2023-12-31 00:00:00       49.000000
std     288.819436                  NaN       14.055953

In [414]:
new_df4 = df4.copy()
new_df4 = pd.get_dummies(new_df4, columns=['ServiceUsage'],drop_first=True, dtype=int)

<h4> Standardization

In [415]:
scaler_lf = StandardScaler()
new_df4['LoginFrequency'] = scaler_lf.fit_transform(new_df4[['LoginFrequency']])

In [416]:
new_df4

,CustomerID,LastLoginDate,LoginFrequency,ServiceUsage_Online Banking,ServiceUsage_Website
0,1,2023-10-21,0.575702,0,0
1,2,2023-12-05,-1.488513,0,1
2,3,2023-11-15,-1.630872,0,1
3,4,2023-08-25,-1.702052,0,1
4,5,2023-10-27,1.073961,0,1
...,...,...,...,...,...
995,996,2023-01-29,0.860422,0,0
996,997,2023-04-01,-1.488513,0,0
997,998,2023-07-10,1.501040,0,1
998,999,2023-01-08,-0.207276,0,1
999,1000,2023-08-13,-0.278455,0,0

<h2>DF5

In [417]:
df5

     CustomerID  ChurnStatus
0             1            0
1             2            1
2             3            0
3             4            0
4             5            0
..          ...          ...
995         996            0
996         997            0
997         998            0
998         999            0
999        1000            0

[1000 rows x 2 columns]

In [418]:
df5.describe()

        CustomerID  ChurnStatus
count  1000.000000  1000.000000
mean    500.500000     0.204000
std     288.819436     0.403171
min       1.000000     0.000000
25%     250.750000     0.000000
50%     500.500000     0.000000
75%     750.250000     0.000000
max    1000.000000     1.000000

In [419]:
merged_df = df1.merge(df5, on='CustomerID')

merged_df

     CustomerID  Age Gender MaritalStatus IncomeLevel  ChurnStatus
0             1   62      M        Single         Low            0
1             2   65      M       Married         Low            1
2             3   18      M        Single         Low            0
3             4   21      M       Widowed         Low            0
4             5   21      M      Divorced      Medium            0
..          ...  ...    ...           ...         ...          ...
995         996   54      F        Single         Low            0
996         997   19      M       Widowed        High            0
997         998   47      M       Married         Low            0
998         999   23      M       Widowed        High            0
999        1000   34      M       Widowed         Low            0

[1000 rows x 6 columns]

In [420]:
transaction_summary = df2.groupby('CustomerID')['AmountSpent'].agg(
    ['sum', 'count', 'mean']
).reset_index()
transaction_summary.columns = [
    'CustomerID',
    'TotalSpent',
    'TransactionCount',
    'AvgSpent'
]
interaction_counts = (
    df3.groupby('CustomerID')
    .size()
    .reset_index(name='InteractionCount')
)
transaction_summary

     CustomerID  TotalSpent  TransactionCount    AvgSpent
0             1      416.50                 1  416.500000
1             2     1547.42                 7  221.060000
2             3     1702.98                 6  283.830000
3             4      917.29                 5  183.458000
4             5     2001.49                 8  250.186250
..          ...         ...               ...         ...
995         996      227.25                 1  227.250000
996         997      419.82                 2  209.910000
997         998      252.15                 1  252.150000
998         999     2393.26                 9  265.917778
999        1000     1670.79                 6  278.465000

[1000 rows x 4 columns]

In [421]:
interaction_counts = df3.groupby('CustomerID').size()
interaction_counts

CustomerID
1      1
2      1
3      1
4      2
6      1
      ..
989    2
990    2
992    1
994    2
995    1
Length: 668, dtype: int64

In [422]:
merged_df

     CustomerID  Age Gender MaritalStatus IncomeLevel  ChurnStatus
0             1   62      M        Single         Low            0
1             2   65      M       Married         Low            1
2             3   18      M        Single         Low            0
3             4   21      M       Widowed         Low            0
4             5   21      M      Divorced      Medium            0
..          ...  ...    ...           ...         ...          ...
995         996   54      F        Single         Low            0
996         997   19      M       Widowed        High            0
997         998   47      M       Married         Low            0
998         999   23      M       Widowed        High            0
999        1000   34      M       Widowed         Low            0

[1000 rows x 6 columns]

In [423]:
# Complaint count

complaint_count = (
    df3[df3['InteractionType'] == 'Complaint']
    .groupby('CustomerID')
    .size()
    .reset_index(name='ComplaintCount')
)

# Unresolved count

unresolved_count = (
    df3[df3['ResolutionStatus'] == 'Unresolved']
    .groupby('CustomerID')
    .size()
    .reset_index(name='UnresolvedCount')
)

# Merge transaction summary

merged_df = merged_df.merge(
    transaction_summary,
    on='CustomerID',
    how='left'
)

# Merge interaction counts

merged_df = merged_df.merge(
    interaction_counts.reset_index(name='InteractionCount'),
    on='CustomerID',
    how='left'
)

# Merge complaint counts

merged_df = merged_df.merge(
    complaint_count,
    on='CustomerID',
    how='left'
)

# Merge unresolved counts

merged_df = merged_df.merge(
    unresolved_count,
    on='CustomerID',
    how='left'
)

# Merge login/service dataset

merged_df = merged_df.merge(
    df4,
    on='CustomerID',
    how='left'
)

# Fill missing values

merged_df = merged_df.fillna(0)

# Inspect final merged dataset

merged_df.head()

merged_df.info()

merged_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Gender            1000 non-null   str
 3   MaritalStatus     1000 non-null   str
 4   IncomeLevel       1000 non-null   str
 5   ChurnStatus       1000 non-null   int64
 6   TotalSpent        1000 non-null   float64
 7   TransactionCount  1000 non-null   int64
 8   AvgSpent          1000 non-null   float64
 9   InteractionCount  1000 non-null   float64
 10  ComplaintCount    1000 non-null   float64
 11  UnresolvedCount   1000 non-null   float64
 12  LastLoginDate     1000 non-null   datetime64[us]
 13  LoginFrequency    1000 non-null   int64
 14  ServiceUsage      1000 non-null   str
dtypes: datetime64[us](1), float64(5), int64(5), str(4)
memory usage: 117.3 KB

,CustomerID,Age,ChurnStatus,TotalSpent,TransactionCount,AvgSpent,InteractionCount,ComplaintCount,UnresolvedCount,LastLoginDate,LoginFrequency
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000
mean,500.500000,43.267000,0.204000,1267.074950,5.054000,248.806511,1.002000,0.335000,0.479000,2023-07-05 21:28:48,25.912000
min,1.000000,18.000000,0.000000,9.800000,1.000000,9.800000,0.000000,0.000000,0.000000,2023-01-01 00:00:00,1.000000
25%,250.750000,30.000000,0.000000,626.685000,3.000000,203.734167,0.000000,0.000000,0.000000,2023-04-08 00:00:00,13.750000
50%,500.500000,43.000000,0.000000,1232.880000,5.000000,250.121458,1.000000,0.000000,0.000000,2023-07-10 12:00:00,27.000000
75%,750.250000,56.000000,0.000000,1791.902500,7.000000,295.023854,2.000000,1.000000,1.000000,2023-10-01 06:00:00,38.000000
max,1000.000000,69.000000,1.000000,3386.040000,9.000000,496.990000,2.000000,2.000000,2.000000,2023-12-31 00:00:00,49.000000
std,288.819436,15.242311,0.403171,738.590013,2.603433,79.372766,0.816494,0.546877,0.621245,NaN,14.055953

In [424]:
model_df = merged_df.copy()

In [425]:
# Gender encoding
model_df['Gender'] = model_df['Gender'].map({
    'M': 0,
    'F': 1
})

# Income level encoding
model_df['IncomeLevel'] = model_df['IncomeLevel'].map({
    'Low': 0,
    'Medium': 1,
    'High': 2
})

In [426]:
model_df = pd.get_dummies(
    model_df,
    columns=[
        'MaritalStatus',
        'ServiceUsage'
    ],
    drop_first=True,
    dtype=int
)

model_df.head()

,CustomerID,Age,Gender,IncomeLevel,ChurnStatus,TotalSpent,TransactionCount,AvgSpent,InteractionCount,ComplaintCount,UnresolvedCount,LastLoginDate,LoginFrequency,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,ServiceUsage_Online Banking,ServiceUsage_Website
0,1,62,0,0,0,416.50,1,416.50000,1.0,0.0,0.0,2023-10-21,34,0,1,0,0,0
1,2,65,0,0,1,1547.42,7,221.06000,1.0,0.0,0.0,2023-12-05,5,1,0,0,0,1
2,3,18,0,0,0,1702.98,6,283.83000,1.0,0.0,0.0,2023-11-15,3,0,1,0,0,1
3,4,21,0,0,0,917.29,5,183.45800,2.0,0.0,1.0,2023-08-25,2,0,0,1,0,1
4,5,21,0,1,0,2001.49,8,250.18625,0.0,0.0,0.0,2023-10-27,41,0,0,0,0,1

In [427]:
scaler = StandardScaler()

numerical_cols = [
    'Age',
    'TotalSpent',
    'AvgSpent',
    'TransactionCount',
    'InteractionCount',
    'ComplaintCount',
    'UnresolvedCount',
    'LoginFrequency'
]

model_df[numerical_cols] = scaler.fit_transform(
    model_df[numerical_cols]
)

model_df.head()

,CustomerID,Age,Gender,IncomeLevel,ChurnStatus,TotalSpent,TransactionCount,AvgSpent,InteractionCount,ComplaintCount,UnresolvedCount,LastLoginDate,LoginFrequency,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,ServiceUsage_Online Banking,ServiceUsage_Website
0,1,1.229628,0,0,0,-1.152196,-1.557954,2.113790,-0.002451,-0.612876,-0.771419,2023-10-21,0.575702,0,1,0,0,0
1,2,1.426547,0,0,1,0.379758,0.747849,-0.349747,-0.002451,-0.612876,-0.771419,2023-12-05,-1.488513,1,0,0,0,1
2,3,-1.658518,0,0,0,0.590481,0.363548,0.441474,-0.002451,-0.612876,-0.771419,2023-11-15,-1.630872,0,1,0,0,1
3,4,-1.461599,0,0,0,-0.473822,-0.020752,-0.823723,1.222911,-0.612876,0.839059,2023-08-25,-1.702052,0,0,1,0,1
4,5,-1.461599,0,1,0,0.994845,1.132149,0.017392,-1.227812,-0.612876,-0.771419,2023-10-27,1.073961,0,0,0,0,1

<h1> EDA